# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Dyte Obj-C Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dyte Obj-C Sample
  pod 'AFNetworking'
  pod 'DyteSdk', '1.34.1'
end
